Watching for file changes with StatReloader
Обработка представления "Index"
Обработка представления "AnimeView"
Обработка представления "Index"
Обработка представления "SignInUserView"
Обработка представления "SignInUserView"
Обработка представления "Index"
Internal Server Error: /profile/transaction
Traceback (most recent call last):
  File "/home/marselle/Asorti/RestFramework/MySiteRestApi/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/marselle/Asorti/RestFramework/MySiteRestApi/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/marselle/Asorti/RestFramework/MySiteRestApi/main/views.py", line 300, in TransactionView
    return render(request, 'Transaction/transaction.html', {'form': form})
  File "/home/marselle/Asorti/RestFramework/MySiteRestApi/venv/lib/python3.10/site-packages/django/shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/marselle/Asorti/RestFramework/MySiteRestApi/venv/lib/python3.10/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/home/marselle/Asorti/RestFramework/MySiteRestApi/venv/lib/python3.10/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/marselle/Asorti/RestFramework/MySiteRestApi/venv/lib/python3.10/site-packages/django/template/base.py", line 175, in render
    return self._render(context)
  File "/home/marselle/Asorti/RestFramework/MySiteRestApi/venv/lib/python3.10/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/home/marselle/Asorti/RestFramework/MySiteRestApi/venv/lib/python3.10/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/marselle/Asorti/RestFramework/MySiteRestApi/venv/lib/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/marselle/Asorti/RestFramework/MySiteRestApi/venv/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/marselle/Asorti/RestFramework/MySiteRestApi/venv/lib/python3.10/site-packages/django/template/loader_tags.py", line 157, in render
    return compiled_parent._render(context)
  File "/home/marselle/Asorti/RestFramework/MySiteRestApi/venv/lib/python3.10/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/home/marselle/Asorti/RestFramework/MySiteRestApi/venv/lib/python3.10/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/marselle/Asorti/RestFramework/MySiteRestApi/venv/lib/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/marselle/Asorti/RestFramework/MySiteRestApi/venv/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/marselle/Asorti/RestFramework/MySiteRestApi/venv/lib/python3.10/site-packages/django/template/loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
  File "/home/marselle/Asorti/RestFramework/MySiteRestApi/venv/lib/python3.10/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/marselle/Asorti/RestFramework/MySiteRestApi/venv/lib/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/marselle/Asorti/RestFramework/MySiteRestApi/venv/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/marselle/Asorti/RestFramework/MySiteRestApi/venv/lib/python3.10/site-packages/django/template/defaulttags.py", line 321, in render
    return nodelist.render(context)
  File "/home/marselle/Asorti/RestFramework/MySiteRestApi/venv/lib/python3.10/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/marselle/Asorti/RestFramework/MySiteRestApi/venv/lib/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/marselle/Asorti/RestFramework/MySiteRestApi/venv/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/marselle/Asorti/RestFramework/MySiteRestApi/venv/lib/python3.10/site-packages/django/template/base.py", line 1070, in render
    return render_value_in_context(output, context)
  File "/home/marselle/Asorti/RestFramework/MySiteRestApi/venv/lib/python3.10/site-packages/django/template/base.py", line 1047, in render_value_in_context
    value = str(value)
  File "/home/marselle/Asorti/RestFramework/MySiteRestApi/venv/lib/python3.10/site-packages/django/utils/html.py", line 420, in <lambda>
    klass.__str__ = lambda self: mark_safe(klass_str(self))
  File "/home/marselle/Asorti/RestFramework/MySiteRestApi/venv/lib/python3.10/site-packages/django/forms/boundfield.py", line 34, in __str__
    return self.as_widget()
  File "/home/marselle/Asorti/RestFramework/MySiteRestApi/venv/lib/python3.10/site-packages/django/forms/boundfield.py", line 107, in as_widget
    return widget.render(
  File "/home/marselle/Asorti/RestFramework/MySiteRestApi/venv/lib/python3.10/site-packages/django/forms/widgets.py", line 280, in render
    context = self.get_context(name, value, attrs)
  File "/home/marselle/Asorti/RestFramework/MySiteRestApi/venv/lib/python3.10/site-packages/django/forms/widgets.py", line 758, in get_context
    context = super().get_context(name, value, attrs)
  File "/home/marselle/Asorti/RestFramework/MySiteRestApi/venv/lib/python3.10/site-packages/django/forms/widgets.py", line 717, in get_context
    context["widget"]["optgroups"] = self.optgroups(
  File "/home/marselle/Asorti/RestFramework/MySiteRestApi/venv/lib/python3.10/site-packages/django/forms/widgets.py", line 657, in optgroups
    for index, (option_value, option_label) in enumerate(self.choices):
  File "/home/marselle/Asorti/RestFramework/MySiteRestApi/venv/lib/python3.10/site-packages/django/forms/models.py", line 1404, in __iter__
    yield self.choice(obj)
  File "/home/marselle/Asorti/RestFramework/MySiteRestApi/venv/lib/python3.10/site-packages/django/forms/models.py", line 1418, in choice
    self.field.label_from_instance(obj),
  File "/home/marselle/Asorti/RestFramework/MySiteRestApi/venv/lib/python3.10/site-packages/django/forms/models.py", line 1504, in label_from_instance
    return str(obj)
  File "/home/marselle/Asorti/RestFramework/MySiteRestApi/main/models.py", line 137, in __str__
    return f"{self.user.first_name.title()} {self.user.last_name.title()[0]}."
IndexError: string index out of range
Обработка представления "UserProfileView"
Обработка представления "UserEditProfileView"
Обработка представления "UserEditProfileView"
Обработка представления "UserProfileView"
Обработка представления "UserEditProfileView"
Обработка представления "UserEditProfileView"
Обработка представления "UserProfileView"
Internal Server Error: /profile/transaction
Traceback (most recent call last):
  File "/home/marselle/Asorti/RestFramework/MySiteRestApi/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/marselle/Asorti/RestFramework/MySiteRestApi/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/marselle/Asorti/RestFramework/MySiteRestApi/main/views.py", line 300, in TransactionView
    return render(request, 'Transaction/transaction.html', {'form': form})
  File "/home/marselle/Asorti/RestFramework/MySiteRestApi/venv/lib/python3.10/site-packages/django/shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/marselle/Asorti/RestFramework/MySiteRestApi/venv/lib/python3.10/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/home/marselle/Asorti/RestFramework/MySiteRestApi/venv/lib/python3.10/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/marselle/Asorti/RestFramework/MySiteRestApi/venv/lib/python3.10/site-packages/django/template/base.py", line 175, in render
    return self._render(context)
  File "/home/marselle/Asorti/RestFramework/MySiteRestApi/venv/lib/python3.10/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/home/marselle/Asorti/RestFramework/MySiteRestApi/venv/lib/python3.10/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/marselle/Asorti/RestFramework/MySiteRestApi/venv/lib/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/marselle/Asorti/RestFramework/MySiteRestApi/venv/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/marselle/Asorti/RestFramework/MySiteRestApi/venv/lib/python3.10/site-packages/django/template/loader_tags.py", line 157, in render
    return compiled_parent._render(context)
  File "/home/marselle/Asorti/RestFramework/MySiteRestApi/venv/lib/python3.10/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/home/marselle/Asorti/RestFramework/MySiteRestApi/venv/lib/python3.10/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/marselle/Asorti/RestFramework/MySiteRestApi/venv/lib/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/marselle/Asorti/RestFramework/MySiteRestApi/venv/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/marselle/Asorti/RestFramework/MySiteRestApi/venv/lib/python3.10/site-packages/django/template/loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
  File "/home/marselle/Asorti/RestFramework/MySiteRestApi/venv/lib/python3.10/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/marselle/Asorti/RestFramework/MySiteRestApi/venv/lib/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/marselle/Asorti/RestFramework/MySiteRestApi/venv/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/marselle/Asorti/RestFramework/MySiteRestApi/venv/lib/python3.10/site-packages/django/template/defaulttags.py", line 321, in render
    return nodelist.render(context)
  File "/home/marselle/Asorti/RestFramework/MySiteRestApi/venv/lib/python3.10/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/marselle/Asorti/RestFramework/MySiteRestApi/venv/lib/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/marselle/Asorti/RestFramework/MySiteRestApi/venv/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/marselle/Asorti/RestFramework/MySiteRestApi/venv/lib/python3.10/site-packages/django/template/base.py", line 1070, in render
    return render_value_in_context(output, context)
  File "/home/marselle/Asorti/RestFramework/MySiteRestApi/venv/lib/python3.10/site-packages/django/template/base.py", line 1047, in render_value_in_context
    value = str(value)
  File "/home/marselle/Asorti/RestFramework/MySiteRestApi/venv/lib/python3.10/site-packages/django/utils/html.py", line 420, in <lambda>
    klass.__str__ = lambda self: mark_safe(klass_str(self))
  File "/home/marselle/Asorti/RestFramework/MySiteRestApi/venv/lib/python3.10/site-packages/django/forms/boundfield.py", line 34, in __str__
    return self.as_widget()
  File "/home/marselle/Asorti/RestFramework/MySiteRestApi/venv/lib/python3.10/site-packages/django/forms/boundfield.py", line 107, in as_widget
    return widget.render(
  File "/home/marselle/Asorti/RestFramework/MySiteRestApi/venv/lib/python3.10/site-packages/django/forms/widgets.py", line 280, in render
    context = self.get_context(name, value, attrs)
  File "/home/marselle/Asorti/RestFramework/MySiteRestApi/venv/lib/python3.10/site-packages/django/forms/widgets.py", line 758, in get_context
    context = super().get_context(name, value, attrs)
  File "/home/marselle/Asorti/RestFramework/MySiteRestApi/venv/lib/python3.10/site-packages/django/forms/widgets.py", line 717, in get_context
    context["widget"]["optgroups"] = self.optgroups(
  File "/home/marselle/Asorti/RestFramework/MySiteRestApi/venv/lib/python3.10/site-packages/django/forms/widgets.py", line 657, in optgroups
    for index, (option_value, option_label) in enumerate(self.choices):
  File "/home/marselle/Asorti/RestFramework/MySiteRestApi/venv/lib/python3.10/site-packages/django/forms/models.py", line 1404, in __iter__
    yield self.choice(obj)
  File "/home/marselle/Asorti/RestFramework/MySiteRestApi/venv/lib/python3.10/site-packages/django/forms/models.py", line 1418, in choice
    self.field.label_from_instance(obj),
  File "/home/marselle/Asorti/RestFramework/MySiteRestApi/venv/lib/python3.10/site-packages/django/forms/models.py", line 1504, in label_from_instance
    return str(obj)
  File "/home/marselle/Asorti/RestFramework/MySiteRestApi/main/models.py", line 137, in __str__
    return f"{self.user.first_name.title()} {self.user.last_name.title()[0]}."
IndexError: string index out of range
Обработка представления "UserProfileView"
Обработка представления "Index"
Watching for file changes with StatReloader
Обработка представления "Index"
Обработка представления "Posts"
Обработка представления "ContactView"
Обработка представления "AnimeView"
Обработка представления "SignInUserView"
Обработка представления "SignInUserView"
Обработка представления "Index"
Обработка представления "Index"
Обработка представления "Posts"
Обработка представления "ContactView"
Обработка представления "AnimeView"
Обработка представления "Index"
Watching for file changes with StatReloader
Обработка представления "Index"
Watching for file changes with StatReloader
Обработка представления "Index"
Обработка представления "SignInUserView"
Обработка представления "SignInUserView"
Обработка представления "SignInUserView"
Обработка представления "SignInUserView"
Обработка представления "SignInUserView"
Watching for file changes with StatReloader
Обработка представления "Index"
Обработка представления "SignInUserView"
Обработка представления "SignInUserView"
Обработка представления "Index"
Internal Server Error: /profile/transaction
Traceback (most recent call last):
  File "/Users/apple/LessonITC/fromgimarsell/MySiteRestApi/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/apple/LessonITC/fromgimarsell/MySiteRestApi/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/apple/LessonITC/fromgimarsell/MySiteRestApi/main/views.py", line 299, in TransactionView
    if request.user.is_authenticated():
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'bool' object is not callable
Internal Server Error: /profile/transaction
Traceback (most recent call last):
  File "/Users/apple/LessonITC/fromgimarsell/MySiteRestApi/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/apple/LessonITC/fromgimarsell/MySiteRestApi/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/apple/LessonITC/fromgimarsell/MySiteRestApi/main/views.py", line 299, in TransactionView
    if request.user.is_authenticated():
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'bool' object is not callable
Watching for file changes with StatReloader
Обработка представления "Index"
Internal Server Error: /profile/transaction
Traceback (most recent call last):
  File "/Users/apple/LessonITC/fromgimarsell/MySiteRestApi/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/apple/LessonITC/fromgimarsell/MySiteRestApi/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/apple/LessonITC/fromgimarsell/MySiteRestApi/main/views.py", line 299, in TransactionView
    if request.user.is_authenticated():
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'bool' object is not callable
Watching for file changes with StatReloader
Обработка представления "Index"
Internal Server Error: /profile/transaction
Traceback (most recent call last):
  File "/Users/apple/LessonITC/fromgimarsell/MySiteRestApi/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/apple/LessonITC/fromgimarsell/MySiteRestApi/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/apple/LessonITC/fromgimarsell/MySiteRestApi/main/views.py", line 299, in TransactionView
    if request.user.is_authenticated():
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'bool' object is not callable
Internal Server Error: /profile/transaction
Traceback (most recent call last):
  File "/Users/apple/LessonITC/fromgimarsell/MySiteRestApi/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/apple/LessonITC/fromgimarsell/MySiteRestApi/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/apple/LessonITC/fromgimarsell/MySiteRestApi/main/views.py", line 299, in TransactionView
    if request.user.is_authenticated():
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'bool' object is not callable
Internal Server Error: /profile/transaction
Traceback (most recent call last):
  File "/Users/apple/LessonITC/fromgimarsell/MySiteRestApi/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/apple/LessonITC/fromgimarsell/MySiteRestApi/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/apple/LessonITC/fromgimarsell/MySiteRestApi/main/views.py", line 299, in TransactionView
    if request.user.is_authenticated():
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'bool' object is not callable
/Users/apple/LessonITC/fromgimarsell/MySiteRestApi/main/views.py changed, reloading.
Watching for file changes with StatReloader
Обработка представления "Index"
/Users/apple/LessonITC/fromgimarsell/MySiteRestApi/main/forms.py changed, reloading.
Watching for file changes with StatReloader
Обработка представления "Index"
Watching for file changes with StatReloader
Обработка представления "Index"
/Users/apple/LessonITC/fromgimarsell/MySiteRestApi/main/admin.py changed, reloading.
Watching for file changes with StatReloader
/Users/apple/LessonITC/fromgimarsell/MySiteRestApi/main/admin.py changed, reloading.
Watching for file changes with StatReloader
/Users/apple/LessonITC/fromgimarsell/MySiteRestApi/main/admin.py changed, reloading.
Watching for file changes with StatReloader
/Users/apple/LessonITC/fromgimarsell/MySiteRestApi/main/admin.py changed, reloading.
Watching for file changes with StatReloader
Обработка представления "Index"
Watching for file changes with StatReloader
Обработка представления "Index"
Internal Server Error: /profile/transaction
Traceback (most recent call last):
  File "/Users/apple/LessonITC/fromgimarsell/MySiteRestApi/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/apple/LessonITC/fromgimarsell/MySiteRestApi/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/apple/LessonITC/fromgimarsell/MySiteRestApi/main/views.py", line 305, in TransactionView
    transaction.save()
  File "/Users/apple/LessonITC/fromgimarsell/MySiteRestApi/main/models.py", line 190, in save
    if self.sender.balance < self.summa:
       ^^^^^^^^^^^
AttributeError: 'Transaction' object has no attribute 'sender'
/Users/apple/LessonITC/fromgimarsell/MySiteRestApi/main/views.py changed, reloading.
Watching for file changes with StatReloader
/Users/apple/LessonITC/fromgimarsell/MySiteRestApi/main/urls.py changed, reloading.
Watching for file changes with StatReloader
/Users/apple/LessonITC/fromgimarsell/MySiteRestApi/main/urls.py changed, reloading.
Watching for file changes with StatReloader
/Users/apple/LessonITC/fromgimarsell/MySiteRestApi/main/urls.py changed, reloading.
Watching for file changes with StatReloader
Обработка представления "Index"
Internal Server Error: /profile/transaction/
Traceback (most recent call last):
  File "/Users/apple/LessonITC/fromgimarsell/MySiteRestApi/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/apple/LessonITC/fromgimarsell/MySiteRestApi/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/apple/LessonITC/fromgimarsell/MySiteRestApi/main/views.py", line 305, in TransactionView
    transaction.save()
  File "/Users/apple/LessonITC/fromgimarsell/MySiteRestApi/main/models.py", line 190, in save
    if self.sender.balance < self.summa:
       ^^^^^^^^^^^
AttributeError: 'Transaction' object has no attribute 'sender'
/Users/apple/LessonITC/fromgimarsell/MySiteRestApi/main/views.py changed, reloading.
Watching for file changes with StatReloader
Обработка представления "Index"
Internal Server Error: /profile/transaction/
Traceback (most recent call last):
  File "/Users/apple/LessonITC/fromgimarsell/MySiteRestApi/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/apple/LessonITC/fromgimarsell/MySiteRestApi/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/apple/LessonITC/fromgimarsell/MySiteRestApi/main/views.py", line 313, in TransactionView
    'transaction': Transaction.objects.get(
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/apple/LessonITC/fromgimarsell/MySiteRestApi/venv/lib/python3.11/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/apple/LessonITC/fromgimarsell/MySiteRestApi/venv/lib/python3.11/site-packages/django/db/models/query.py", line 637, in get
    raise self.model.DoesNotExist(
main.models.Transaction.DoesNotExist: Transaction matching query does not exist.
/Users/apple/LessonITC/fromgimarsell/MySiteRestApi/main/views.py changed, reloading.
Watching for file changes with StatReloader
Обработка представления "Index"
Internal Server Error: /profile/transaction/
Traceback (most recent call last):
  File "/Users/apple/LessonITC/fromgimarsell/MySiteRestApi/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/apple/LessonITC/fromgimarsell/MySiteRestApi/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/apple/LessonITC/fromgimarsell/MySiteRestApi/main/views.py", line 313, in TransactionView
    'transactions': Transaction.objects.get(
                    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/apple/LessonITC/fromgimarsell/MySiteRestApi/venv/lib/python3.11/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/apple/LessonITC/fromgimarsell/MySiteRestApi/venv/lib/python3.11/site-packages/django/db/models/query.py", line 637, in get
    raise self.model.DoesNotExist(
main.models.Transaction.DoesNotExist: Transaction matching query does not exist.
Watching for file changes with StatReloader
Обработка представления "Index"
Internal Server Error: /profile/transaction/
Traceback (most recent call last):
  File "/Users/apple/LessonITC/fromgimarsell/MySiteRestApi/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/apple/LessonITC/fromgimarsell/MySiteRestApi/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/apple/LessonITC/fromgimarsell/MySiteRestApi/main/views.py", line 313, in TransactionView
    'transactions': Transaction.objects.get(
                    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/apple/LessonITC/fromgimarsell/MySiteRestApi/venv/lib/python3.11/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/apple/LessonITC/fromgimarsell/MySiteRestApi/venv/lib/python3.11/site-packages/django/db/models/query.py", line 637, in get
    raise self.model.DoesNotExist(
main.models.Transaction.DoesNotExist: Transaction matching query does not exist.
Internal Server Error: /profile/transaction/
Traceback (most recent call last):
  File "/Users/apple/LessonITC/fromgimarsell/MySiteRestApi/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/apple/LessonITC/fromgimarsell/MySiteRestApi/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/apple/LessonITC/fromgimarsell/MySiteRestApi/main/views.py", line 313, in TransactionView
    'transactions': Transaction.objects.get(
                    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/apple/LessonITC/fromgimarsell/MySiteRestApi/venv/lib/python3.11/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/apple/LessonITC/fromgimarsell/MySiteRestApi/venv/lib/python3.11/site-packages/django/db/models/query.py", line 637, in get
    raise self.model.DoesNotExist(
main.models.Transaction.DoesNotExist: Transaction matching query does not exist.
Internal Server Error: /profile/transaction/
Traceback (most recent call last):
  File "/Users/apple/LessonITC/fromgimarsell/MySiteRestApi/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/apple/LessonITC/fromgimarsell/MySiteRestApi/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/apple/LessonITC/fromgimarsell/MySiteRestApi/main/views.py", line 313, in TransactionView
    'transactions': Transaction.objects.get(
                    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/apple/LessonITC/fromgimarsell/MySiteRestApi/venv/lib/python3.11/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/apple/LessonITC/fromgimarsell/MySiteRestApi/venv/lib/python3.11/site-packages/django/db/models/query.py", line 637, in get
    raise self.model.DoesNotExist(
main.models.Transaction.DoesNotExist: Transaction matching query does not exist.
/Users/apple/LessonITC/fromgimarsell/MySiteRestApi/main/views.py changed, reloading.
Watching for file changes with StatReloader
/Users/apple/LessonITC/fromgimarsell/MySiteRestApi/main/views.py changed, reloading.
Watching for file changes with StatReloader
/Users/apple/LessonITC/fromgimarsell/MySiteRestApi/main/views.py changed, reloading.
Watching for file changes with StatReloader
Обработка представления "Index"
Internal Server Error: /profile/transaction/
Traceback (most recent call last):
  File "/Users/apple/LessonITC/fromgimarsell/MySiteRestApi/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/apple/LessonITC/fromgimarsell/MySiteRestApi/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/apple/LessonITC/fromgimarsell/MySiteRestApi/main/views.py", line 311, in TransactionView
    transactions = Transaction.objects.filter({
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/apple/LessonITC/fromgimarsell/MySiteRestApi/venv/lib/python3.11/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/apple/LessonITC/fromgimarsell/MySiteRestApi/venv/lib/python3.11/site-packages/django/db/models/query.py", line 1436, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/apple/LessonITC/fromgimarsell/MySiteRestApi/venv/lib/python3.11/site-packages/django/db/models/query.py", line 1454, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "/Users/apple/LessonITC/fromgimarsell/MySiteRestApi/venv/lib/python3.11/site-packages/django/db/models/query.py", line 1461, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/Users/apple/LessonITC/fromgimarsell/MySiteRestApi/venv/lib/python3.11/site-packages/django/db/models/sql/query.py", line 1534, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/apple/LessonITC/fromgimarsell/MySiteRestApi/venv/lib/python3.11/site-packages/django/db/models/sql/query.py", line 1565, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "/Users/apple/LessonITC/fromgimarsell/MySiteRestApi/venv/lib/python3.11/site-packages/django/db/models/sql/query.py", line 1391, in build_filter
    raise FieldError("Cannot parse keyword query as dict")
django.core.exceptions.FieldError: Cannot parse keyword query as dict
/Users/apple/LessonITC/fromgimarsell/MySiteRestApi/main/views.py changed, reloading.
Watching for file changes with StatReloader
Обработка представления "Index"
Internal Server Error: /profile/transaction/
Traceback (most recent call last):
  File "/Users/apple/LessonITC/fromgimarsell/MySiteRestApi/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/apple/LessonITC/fromgimarsell/MySiteRestApi/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/apple/LessonITC/fromgimarsell/MySiteRestApi/main/views.py", line 315, in TransactionView
    'transactions': transaction,
                    ^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'transaction' where it is not associated with a value
Internal Server Error: /profile/transaction/
Traceback (most recent call last):
  File "/Users/apple/LessonITC/fromgimarsell/MySiteRestApi/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/apple/LessonITC/fromgimarsell/MySiteRestApi/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/apple/LessonITC/fromgimarsell/MySiteRestApi/main/views.py", line 315, in TransactionView
    'transactions': transaction,
                    ^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'transaction' where it is not associated with a value
/Users/apple/LessonITC/fromgimarsell/MySiteRestApi/main/views.py changed, reloading.
Watching for file changes with StatReloader
Обработка представления "Index"
Internal Server Error: /profile/transaction/
Traceback (most recent call last):
  File "/Users/apple/LessonITC/fromgimarsell/MySiteRestApi/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/apple/LessonITC/fromgimarsell/MySiteRestApi/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/apple/LessonITC/fromgimarsell/MySiteRestApi/main/views.py", line 305, in TransactionView
    transaction.save()
  File "/Users/apple/LessonITC/fromgimarsell/MySiteRestApi/main/models.py", line 190, in save
    if self.sender.balance < self.summa:
       ^^^^^^^^^^^
AttributeError: 'Transaction' object has no attribute 'sender'
Internal Server Error: /profile/transaction/
Traceback (most recent call last):
  File "/Users/apple/LessonITC/fromgimarsell/MySiteRestApi/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/apple/LessonITC/fromgimarsell/MySiteRestApi/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/apple/LessonITC/fromgimarsell/MySiteRestApi/main/views.py", line 305, in TransactionView
    transaction.save()
  File "/Users/apple/LessonITC/fromgimarsell/MySiteRestApi/main/models.py", line 190, in save
    if self.sender.balance < self.summa:
       ^^^^^^^^^^^
AttributeError: 'Transaction' object has no attribute 'sender'
/Users/apple/LessonITC/fromgimarsell/MySiteRestApi/main/views.py changed, reloading.
Watching for file changes with StatReloader
Обработка представления "Index"
Internal Server Error: /profile/transaction/
Traceback (most recent call last):
  File "/Users/apple/LessonITC/fromgimarsell/MySiteRestApi/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/apple/LessonITC/fromgimarsell/MySiteRestApi/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/apple/LessonITC/fromgimarsell/MySiteRestApi/main/views.py", line 315, in TransactionView
    'transactions': transaction,
                    ^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'transaction' where it is not associated with a value
/Users/apple/LessonITC/fromgimarsell/MySiteRestApi/main/views.py changed, reloading.
Watching for file changes with StatReloader
Обработка представления "Index"
Internal Server Error: /profile/transaction/
Traceback (most recent call last):
  File "/Users/apple/LessonITC/fromgimarsell/MySiteRestApi/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/apple/LessonITC/fromgimarsell/MySiteRestApi/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/apple/LessonITC/fromgimarsell/MySiteRestApi/main/views.py", line 315, in TransactionView
    'transaction': transaction,
                   ^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'transaction' where it is not associated with a value
/Users/apple/LessonITC/fromgimarsell/MySiteRestApi/main/views.py changed, reloading.
Watching for file changes with StatReloader
Обработка представления "Index"
Обработка представления "Index"
Internal Server Error: /profile/transaction/
Traceback (most recent call last):
  File "/Users/apple/LessonITC/fromgimarsell/MySiteRestApi/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/apple/LessonITC/fromgimarsell/MySiteRestApi/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/apple/LessonITC/fromgimarsell/MySiteRestApi/main/views.py", line 305, in TransactionView
    transaction.save()
  File "/Users/apple/LessonITC/fromgimarsell/MySiteRestApi/main/models.py", line 190, in save
    if self.sender.balance < self.summa:
       ^^^^^^^^^^^
AttributeError: 'Transaction' object has no attribute 'sender'
/Users/apple/LessonITC/fromgimarsell/MySiteRestApi/main/models.py changed, reloading.
Watching for file changes with StatReloader
/Users/apple/LessonITC/fromgimarsell/MySiteRestApi/main/models.py changed, reloading.
Watching for file changes with StatReloader
Обработка представления "Index"
/Users/apple/LessonITC/fromgimarsell/MySiteRestApi/main/urls.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /profile/transaction/
Traceback (most recent call last):
  File "/Users/apple/LessonITC/fromgimarsell/MySiteRestApi/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/apple/LessonITC/fromgimarsell/MySiteRestApi/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/apple/LessonITC/fromgimarsell/MySiteRestApi/main/views.py", line 305, in TransactionView
    transaction.save()
  File "/Users/apple/LessonITC/fromgimarsell/MySiteRestApi/main/models.py", line 171, in save
    raise Exception("Недостаточно средств на балансе отправителя")
Exception: Недостаточно средств на балансе отправителя
Internal Server Error: /profile/transaction/
Traceback (most recent call last):
  File "/Users/apple/LessonITC/fromgimarsell/MySiteRestApi/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/apple/LessonITC/fromgimarsell/MySiteRestApi/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/apple/LessonITC/fromgimarsell/MySiteRestApi/main/views.py", line 305, in TransactionView
    transaction.save()
  File "/Users/apple/LessonITC/fromgimarsell/MySiteRestApi/main/models.py", line 171, in save
    raise Exception("Недостаточно средств на балансе отправителя")
Exception: Недостаточно средств на балансе отправителя
Internal Server Error: /profile/transaction/
Traceback (most recent call last):
  File "/Users/apple/LessonITC/fromgimarsell/MySiteRestApi/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/apple/LessonITC/fromgimarsell/MySiteRestApi/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/apple/LessonITC/fromgimarsell/MySiteRestApi/main/views.py", line 305, in TransactionView
    transaction.save()
  File "/Users/apple/LessonITC/fromgimarsell/MySiteRestApi/main/models.py", line 171, in save
    raise Exception("Недостаточно средств на балансе отправителя")
Exception: Недостаточно средств на балансе отправителя
Обработка представления "Index"
Обработка представления "Index"
/Users/apple/LessonITC/fromgimarsell/MySiteRestApi/main/views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Обработка представления "Index"
Обработка представления "UserProfileView"
Обработка представления "UserProfileView"
/Users/apple/LessonITC/fromgimarsell/MySiteRestApi/main/views.py changed, reloading.
Watching for file changes with StatReloader
/Users/apple/LessonITC/fromgimarsell/MySiteRestApi/main/views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Обработка представления "Index"
Обработка представления "UserProfileView"
Обработка представления "Index"
Обработка представления "Posts"
Обработка представления "ContactView"
Обработка представления "AnimeView"
Not Found: /favicon.ico
